### ISSUE TITLE
Change active control at window open

### ISSUE THREAD

**Issue by rangerxusa** [KN4CK3R/KeePassTimestampChanger#1]
Nice KeePass plugin. Very useful for quickly check the dates of an entry.
I use the plugin to view dates and rarely if ever change the dates. When the window opens the active control is the created date's month field which is show in dark blue (selected). This makes it hard to read the date without pressing shift-tab. I would like to make the "created" checkbox the active control when the window opens to make it more easily readable.
I looked at the code and do understand it and also how to compile the plugin. But I do not understand forms and how to change your plugin to make the "created" checkbox the active control. Searching the Internet was not helpful. 
If it doesn't make sense for you to change your plugin, can you tell me what I would need to add/change in the code to make the "created" checkbox the active control and where to make this change myself.
Thanks!

**Comment by JanisEst** [comment]
What you are searching for is called "TabIndex", the order in which you can jump through the controls with the tab key. The control with TabIndex = 0 is autofocused for a new form. To remove the autofocus of the DateTimePicker you can choose an other  control like the checkbox.

Change these lines in the ModifyEntryTimestampsForm.Designer.cs file (or set the values in the designer). That should fix your problem. If not ask again here.
```
this.createdCheckBox.TabIndex = 0;
this.createdDateTimePicker.TabIndex = 1;
this.lastModifiedCheckBox.TabIndex = 2;
this.lastModifiedDateTimePicker.TabIndex = 3;
this.lastAccessedCheckBox.TabIndex = 4;
this.lastAccessedDateTimePicker.TabIndex = 5;
this.okButton.TabIndex = 6;
this.cancelButton.TabIndex = 7;
```

**Comment by rangerxusa** [comment]
Thanks much. That worked and I was able to change the active control. Thanks again.
